#!/usr/bin/env perl
# This file is generated by `note'.
# See https://github.com/aralsea/note

# LaTeX
$latex = 'pdflatex -interaction=nonstopmode -file-line-error -halt-on-error %O %S';
$max_repeat = 5;

# # BibTeX
$bibtex = 'bibtex %O %S';
$biber = 'biber --bblencoding=utf8 -u -U --output_safechars %O %S';

# DVI / PDF
$pdf_mode = 1; # use pdflatex

# output directory 
# この.latexmkrcと同じディレクトリにあるoutディレクトリに出力する
{
    use Cwd;
    my $current_dir_path = Cwd::getcwd();
    print "current directory path: $current_dir_path\n";

    my $rc_file_path = "$current_dir_path/.latexmkrc"; # この.latexmkrcファイルの絶対パス。もしこのファイルと同じディレクトリでlatexmkが実行されたならこれでok

    # -r オプションでこの.latexmkrcファイルを指定していた場合はこっち
    for my $arg ( @ARGV ){
        if( $arg =~ /\.latexmkrc$/ ){
            $rc_file_path = ($arg=~m!^/!)? $arg : "$current_dir_path/$arg";
        }
    }
    print "latexmkrc file path: $rc_file_path\n";

    my $project_dir_path = $rc_file_path =~ s/\/\.latexmkrc$//r;

    $out_dir = "$project_dir_path/out"; # e.g. /Users/username/project1/out
    print "output directory path: $out_dir\n";
}
